let lastMainScrollPosition=0;document.addEventListener('DOMContentLoaded',function(){const mainContent=document.getElementById('main-content');const projectPages=document.querySelectorAll('[id^="project"]');const viewProjectButtons=document.querySelectorAll('.view-project-btn');const backButtons=document.querySelectorAll('.back-to-main');const mobileNav=document.getElementById('mobile-nav');const mobileNavLinks=document.querySelectorAll('.nav-mobile-link');const textNavLinks=document.querySelectorAll('.nav-link');const updateActiveHighlight=(targetId)=>{textNavLinks.forEach(link=>link.classList.remove('active-nav'));mobileNavLinks.forEach(link=>link.classList.remove('active-icon'));const cleanTargetId=targetId||'#about';textNavLinks.forEach(link=>{if(link.getAttribute('href')===cleanTargetId){link.classList.add('active-nav')}});mobileNavLinks.forEach(link=>{if(link.getAttribute('href')===cleanTargetId){link.classList.add('active-icon')}})};const showPage=(pageId,isPopState=!1,targetSectionId=null,restoreScroll=!1)=>{if(pageId!=='main-content'&&!isPopState){window.scrollTo(0,0)}
mainContent.classList.remove('active');projectPages.forEach(page=>page.classList.remove('active'));if(pageId!=='main-content'){textNavLinks.forEach(link=>link.classList.remove('active-nav'));mobileNavLinks.forEach(link=>link.classList.remove('active-icon'))}
let newHash='';if(pageId==='main-content'||!pageId){pageId='main-content';mainContent.classList.add('active');mobileNav.classList.remove('hidden');if(restoreScroll){setTimeout(()=>{window.scrollTo({top:lastMainScrollPosition,behavior:'auto'});observer.takeRecords();observer.observe(document.querySelector('#portfolio'))},0);newHash='#portfolio'}else if(isPopState){updateActiveHighlight(window.location.hash||'#about');newHash=window.location.hash||' '}else{const target=targetSectionId||'#about';updateActiveHighlight(target);setTimeout(()=>{const targetElement=document.querySelector(target);if(targetElement){targetElement.scrollIntoView({behavior:'smooth'})}},50);newHash=target}}else{const projectPage=document.getElementById(pageId);if(projectPage){projectPage.classList.add('active');mobileNav.classList.remove('hidden');if(pageId==='project14'||pageId==='project15'){setTimeout(initProjectCharts,50)}else if(pageId==='project1'){setTimeout(setupProject1Slider,50)}
newHash='#'+pageId}else{mainContent.classList.add('active');mobileNav.classList.remove('hidden');updateActiveHighlight('#about');pageId='main-content';newHash=' '}}
if(!isPopState){const historyHash=(newHash==='#about'||newHash===' ')?' ':newHash;history.pushState({page:pageId,targetSection:targetSectionId},'',historyHash)}};const initialHash=window.location.hash;if(initialHash&&initialHash.startsWith('#project')){const pageId=initialHash.substring(1);showPage(pageId);if(pageId==='project1'){setTimeout(setupProject1Slider,50)}else if(pageId==='project14'||pageId==='project15'){setTimeout(initProjectCharts,50)}
history.replaceState({page:pageId},'',initialHash)}else{const targetSection=(initialHash&&initialHash!=='#')?initialHash:'#about';showPage('main-content',!1,targetSection,!1);history.replaceState({page:'main-content',targetSection:targetSection},'',targetSection==='#about'?' ':targetSection)}
viewProjectButtons.forEach(button=>{button.addEventListener('click',()=>{lastMainScrollPosition=window.scrollY;const currentState=history.state||{};history.replaceState({...currentState,scrollY:lastMainScrollPosition},'',window.location.hash);const pageId=button.dataset.page;showPage(pageId,!1,null,!1)})});backButtons.forEach(button=>{button.addEventListener('click',(e)=>{e.preventDefault();const targetId=button.getAttribute('href');if(targetId==='#portfolio'){showPage('main-content',!1,null,!0)}else{showPage('main-content',!1,targetId,!1)}})});mobileNavLinks.forEach(link=>{link.addEventListener('click',(e)=>{e.preventDefault();const targetId=link.getAttribute('href');showPage('main-content',!1,targetId,!1)})});window.addEventListener('popstate',(event)=>{const pageToLoad=(event.state&&event.state.page)?event.state.page:'main-content';showPage(pageToLoad,!0);if(pageToLoad==='project1'){setTimeout(setupProject1Slider,50)}else if(pageToLoad==='project14'||pageToLoad==='project15'){setTimeout(initProjectCharts,50)}});const sections=document.querySelectorAll('#main-content section');const observerOptions={root:null,rootMargin:'0px',threshold:0.4};const observer=new IntersectionObserver((entries)=>{if(!mainContent.classList.contains('active')){return}
let foundActive=!1;entries.forEach(entry=>{if(entry.isIntersecting){foundActive=!0;const activeId='#'+entry.target.id;updateActiveHighlight(activeId)}})},observerOptions);sections.forEach(section=>{if(section.id)observer.observe(section);});const filterButtons=document.querySelectorAll('.filter-btn');const portfolioItems=document.querySelectorAll('.portfolio-item');filterButtons.forEach(button=>{button.addEventListener('click',()=>{filterButtons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;portfolioItems.forEach(item=>{item.style.display='none';if(filter==='all'||item.dataset.category===filter){item.style.display='block'}})})})});document.addEventListener('click',function(e){const openBtn=e.target.closest('[data-open]');if(openBtn){e.preventDefault();const id=openBtn.getAttribute('data-open');const modal=document.getElementById(id);if(modal){modal.style.display='flex';modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
return}
const closeBtn=e.target.closest('[data-close]');if(closeBtn){e.preventDefault();const backdrop=closeBtn.closest('.modal-backdrop');if(backdrop){backdrop.style.display='none';backdrop.setAttribute('aria-hidden','true');document.body.style.overflow='auto'}
return}
if(e.target.classList.contains('modal-backdrop')){e.target.style.display='none';e.target.setAttribute('aria-hidden','true');document.body.style.overflow='auto';return}
const tabBtn=e.target.closest('.p18-tab-btn');if(tabBtn){e.preventDefault();const targetId=tabBtn.dataset.target;const targetContent=document.getElementById(targetId);const tabContainer=tabBtn.closest('.p18-tabs');const contentContainer=tabContainer?.nextElementSibling;if(tabContainer){tabContainer.querySelectorAll('.p18-tab-btn').forEach(btn=>{btn.classList.remove('active')})}
tabBtn.classList.add('active');if(contentContainer){contentContainer.querySelectorAll('.p18-tab-content').forEach(content=>{content.style.display='none'});if(targetContent){targetContent.style.display='block'}}
return}});let p14_revenueChartInstance=null;let p14_trafficChartInstance=null;let p15_revenueTrendChartInstance=null;let p15_regionChartInstance=null;let p15_targetChartInstance=null;let p16_activityChartInstance=null;function getGoldenGradient(ctx){if(!ctx)return'rgba(255, 215, 0, 0.1)';const gradient=ctx.createLinearGradient(0,0,0,400);gradient.addColorStop(0,'rgba(255, 215, 0, 0.6)');gradient.addColorStop(1,'rgba(255, 215, 0, 0.01)');return gradient}
function initProjectCharts(){[p14_revenueChartInstance,p14_trafficChartInstance,p15_revenueTrendChartInstance,p15_regionChartInstance,p15_targetChartInstance,p16_activityChartInstance].forEach(instance=>{if(instance)instance.destroy();});const p14_revenueCtx=document.getElementById('p14-revenueChart');if(p14_revenueCtx){const ctx=p14_revenueCtx.getContext('2d');p14_revenueChartInstance=new Chart(ctx,{type:'line',data:{labels:['Week 1','Week 2','Week 3','Week 4','Week 5','Week 6'],datasets:[{label:'Revenue',data:[52000,89432,71000,110500,92000,130000],borderColor:'#FFD700',backgroundColor:getGoldenGradient(ctx),fill:!0,tension:0.4,pointRadius:0,pointHoverRadius:6,pointHoverBackgroundColor:'#FFD700',}]},options:{responsive:!0,maintainAspectRatio:!1,plugins:{legend:{display:!1}},scales:{x:{ticks:{color:'#9ca3af'},grid:{color:'rgba(255, 215, 0, 0.1)'}},y:{ticks:{color:'#9ca3af'},grid:{color:'rgba(255, 215, 0, 0.1)'}}}}})}
const p14_trafficCtx=document.getElementById('p14-trafficChart');if(p14_trafficCtx){p14_trafficChartInstance=new Chart(p14_trafficCtx,{type:'doughnut',data:{labels:['Organic','Direct','Referral'],datasets:[{data:[50,35,15],backgroundColor:['#FFD700','#f0c400','#fff3b0'],borderColor:'rgba(20, 20, 20, 0.6)',borderWidth:4,hoverOffset:10}]},options:{responsive:!0,maintainAspectRatio:!1,cutout:'70%',plugins:{legend:{position:'bottom',labels:{color:'#9ca3af',boxWidth:12,padding:20}}}}})}
const p15_revenueTrendCtx=document.getElementById('p15-revenueTrendChart');if(p15_revenueTrendCtx){const ctx=p15_revenueTrendCtx.getContext('2d');p15_revenueTrendChartInstance=new Chart(ctx,{type:'line',data:{labels:['Jan','Feb','Mar','Apr','May','Jun','Jul'],datasets:[{label:'Revenue',data:[150,180,220,200,250,230,280],borderColor:'#FFD700',backgroundColor:getGoldenGradient(ctx),fill:!0,tension:0.4,pointRadius:0,pointHoverRadius:6,pointHoverBackgroundColor:'#FFD700',}]},options:{responsive:!0,maintainAspectRatio:!1,plugins:{legend:{display:!1}},scales:{x:{ticks:{color:'#9ca3af'},grid:{color:'rgba(255, 215, 0, 0.1)'}},y:{ticks:{color:'#9ca3af'},grid:{color:'rgba(255, 215, 0, 0.1)'}}}}})}
const p15_regionCtx=document.getElementById('p15-regionChart');if(p15_regionCtx){p15_regionChartInstance=new Chart(p15_regionCtx,{type:'doughnut',data:{labels:['North America (35%)','Europe (30%)','APAC (25%)','LATAM (10%)'],datasets:[{data:[35,30,25,10],backgroundColor:['#FFD700','#f0c400','#fff3b0','#FFEA8A'],borderColor:'rgba(20, 20, 20, 0.6)',borderWidth:4,hoverOffset:10}]},options:{responsive:!0,maintainAspectRatio:!1,cutout:'70%',plugins:{legend:{position:'bottom',labels:{color:'#9ca3af',boxWidth:12,padding:15,font:{size:10}}}}}})}
const p15_targetCtx=document.getElementById('p15-targetChart');if(p15_targetCtx){p15_targetChartInstance=new Chart(p15_targetCtx,{type:'doughnut',data:{labels:['Completed','Remaining'],datasets:[{data:[84,16],backgroundColor:['#FFD700','rgba(255, 215, 0, 0.2)'],borderColor:'rgba(20, 20, 20, 0.6)',borderWidth:4,hoverOffset:4,}]},options:{responsive:!0,maintainAspectRatio:!1,cutout:'80%',plugins:{legend:{display:!1},tooltip:{enabled:!1}}}})}
const p16_activityCtx=document.getElementById('p16-activityChart');if(p16_activityCtx){const ctx=p16_activityCtx.getContext('2d');p16_activityChartInstance=new Chart(ctx,{type:'line',data:{labels:['Wk 1','Wk 2','Wk 3','Wk 4','Wk 5','Wk 6','Wk 7','Wk 8'],datasets:[{label:'User Activity',data:[1200,1800,1500,2100,1700,2300,2000,2800],borderColor:'#FFD700',backgroundColor:getGoldenGradient(ctx),fill:!0,tension:0.4,pointRadius:0,pointHoverRadius:6,pointHoverBackgroundColor:'#FFD700',}]},options:{responsive:!0,maintainAspectRatio:!1,plugins:{legend:{display:!1}},scales:{x:{ticks:{color:'#9ca3af'},grid:{display:!1}},y:{ticks:{color:'#9ca3af'},grid:{color:'rgba(255, 215, 0, 0.1)'}}}}})}}
let project1SliderInterval=null;function setupProject1Slider(){const sliderContainer=document.querySelector('#project1 .p1-slider-container');const sliderWrapper=document.querySelector('#project1 .p1-slider-wrapper');const prevButton=document.querySelector('#project1 .p1-slider-prev');const nextButton=document.querySelector('#project1 .p1-slider-next');const dotsContainer=document.querySelector('#project1 .p1-slider-dots');if(project1SliderInterval)clearInterval(project1SliderInterval);if(!sliderContainer||!sliderWrapper||!prevButton||!nextButton||!dotsContainer){return}
const slides=sliderWrapper.querySelectorAll('.p1-slide');if(slides.length<=1){prevButton.style.display='none';nextButton.style.display='none';dotsContainer.style.display='none';return}else{prevButton.style.display='flex';nextButton.style.display='flex'}
let currentIndex=0;let itemsPerView=window.innerWidth>=768?2:1;const totalItems=slides.length;let totalViews=Math.ceil(totalItems/itemsPerView);let maxIndex=Math.max(0,totalViews-1);const autoSlideDelay=4000;function createDots(){dotsContainer.innerHTML='';totalViews=Math.ceil(totalItems/itemsPerView);maxIndex=Math.max(0,totalViews-1);if(totalViews<=1){dotsContainer.style.display='none';return}else{dotsContainer.style.display='flex'}
for(let i=0;i<totalViews;i++){const dot=document.createElement('button');dot.style.width='8px';dot.style.height='8px';dot.style.borderRadius='50%';dot.style.backgroundColor='rgba(255, 215, 0, 0.3)';dot.style.transition='background-color 0.3s ease';dot.setAttribute('aria-label',`Go to slide group ${i + 1}`);if(i===currentIndex){dot.style.backgroundColor='#FFD700'}
dot.addEventListener('click',()=>{currentIndex=i;updateSliderPosition();stopAutoSlide();startAutoSlide()});dotsContainer.appendChild(dot)}}
function updateDots(){const dots=dotsContainer.querySelectorAll('button');dots.forEach((dot,index)=>{dot.style.backgroundColor=index===currentIndex?'#FFD700':'rgba(255, 215, 0, 0.3)'})}
function updateSliderPosition(smooth=!0){if(!slides||slides.length===0)return;const slideWidth=slides[0].offsetWidth;let newTransform=-currentIndex*itemsPerView*slideWidth;const maxScrollWidth=sliderWrapper.scrollWidth-sliderContainer.offsetWidth;let maxTransform=-maxScrollWidth;if(sliderContainer.offsetWidth>sliderWrapper.scrollWidth){maxTransform=0}
newTransform=Math.max(newTransform,maxTransform);newTransform=Math.min(newTransform,0);sliderWrapper.style.transition=smooth?'transform 0.3s ease-in-out':'none';if(currentIndex===maxIndex&&totalItems%itemsPerView!==0&&itemsPerView>1){sliderWrapper.style.transform=`translateX(${maxTransform}px)`}else{sliderWrapper.style.transform=`translateX(${newTransform}px)`}
updateDots()}
function updateItemsPerView(){const oldItemsPerView=itemsPerView;itemsPerView=window.innerWidth>=768?2:1;if(oldItemsPerView!==itemsPerView){const firstVisibleItemIndex=currentIndex*oldItemsPerView;currentIndex=Math.floor(firstVisibleItemIndex/itemsPerView);createDots();currentIndex=Math.min(currentIndex,maxIndex);updateSliderPosition(!1)}else{updateSliderPosition(!1)}}
function goToNextSlide(){if(currentIndex<maxIndex){currentIndex++}else{currentIndex=0}
updateSliderPosition()}
function goToPrevSlide(){if(currentIndex>0){currentIndex--}else{currentIndex=maxIndex}
updateSliderPosition()}
function startAutoSlide(){if(project1SliderInterval)clearInterval(project1SliderInterval);if(totalViews>1){project1SliderInterval=setInterval(goToNextSlide,autoSlideDelay)}}
function stopAutoSlide(){clearInterval(project1SliderInterval)}
nextButton.addEventListener('click',()=>{goToNextSlide();stopAutoSlide();startAutoSlide()});prevButton.addEventListener('click',()=>{goToPrevSlide();stopAutoSlide();startAutoSlide()});sliderContainer.addEventListener('mouseenter',stopAutoSlide);sliderContainer.addEventListener('mouseleave',startAutoSlide);if('ResizeObserver' in window){const resizeObserver=new ResizeObserver(()=>{stopAutoSlide();updateItemsPerView();startAutoSlide()});resizeObserver.observe(sliderContainer)}else{window.addEventListener('resize',()=>{stopAutoSlide();updateItemsPerView();startAutoSlide()})}
createDots();updateItemsPerView();startAutoSlide()}
